### ISSUE TITLE
1.20.4?

### ISSUE THREAD

**Issue by deepore** [Noxmore/Alternative-Dark-UI#2]
Will this resource pack be updated to 1.20.4?

**Comment by Noxmore** [comment]
Are there any issues with 1.20.4 or is it just that it says it's for an older version?

I normally only update my Minecraft every major release, so if there's no issues i'll just update this when 1.21 comes out.

**Comment by Noxmore** [comment]
Just updated, yep, it's broken due to mojang splitting up all the gui textures, just fixed it and released an update on modrinth.
