### ISSUE TITLE
Language and mod support

### ISSUE THREAD

**Issue by thwonn** [Noxmore/Alternative-Dark-UI#3]
The only supported language is currently US English and modded settings and creative tabs do not render text correctly. Could this be fixed by using shaders instead of language files?
It would also be helpful if the patch is released for both 1.20.1 and 1.20.4

**Comment by thwonn** [comment]
These could help
[Archive.zip](https://github.com/Noxmore/Alternative-Dark-UI/files/14824670/Archive.zip)
donʼt give me credit for this, I just stole these from another resource pack ([Mintcraft](https://modrinth.com/resourcepack/mintcraft))

Example of the pack with the Mintcraft files edited in:
[Alternative Dark UI 1.2.zip](https://github.com/Noxmore/Alternative-Dark-UI/files/14827030/Alternative.Dark.UI.1.2.zip)

**Comment by Noxmore** [comment]
This is super cool! I'm glad there's a better way then editing language files. Thank you very much!

As for releasing the patch for both 1.20.1 and 1.20.4, I'm not that good at git, but I've tried separating each version into it's own branch, and released both with the patch, hopefully now it'll be easy to update each version separately in the future!
