### ISSUE TITLE
Fabric inventory tab support

### ISSUE THREAD

**Issue by thwonn** [Noxmore/Alternative-Dark-UI#6]
This resource pack does not yet support the fabric inventory page selectors. Is this planned in the future?
<img width="590" alt="Screenshot 2024-10-20 at 11 27 07" src="https://github.com/user-attachments/assets/990b2dc5-f68b-479f-b340-b881b32ddbe3">
<img width="94" alt="Screenshot 2024-10-20 at 11 27 12" src="https://github.com/user-attachments/assets/77fcdaff-16bd-43e7-b269-ea3fc7e245f0">

**Comment by Noxmore** [comment]
Done, and released in 2.4.
