### ISSUE TITLE
Missing outlines in 1.20.1

### ISSUE THREAD

**Issue by thwonn** [Noxmore/Alternative-Dark-UI#7]
When using the resource pack in 1.20.1, some outlines are missing in the status effect display and gamemode switcher.
<img width="302" alt="Screenshot 2024-10-21 at 06 07 44" src="https://github.com/user-attachments/assets/324c3b1d-1b55-4fa0-b828-5e2d8e8f8a7f">
<img width="473" alt="Screenshot 2024-10-21 at 06 07 58" src="https://github.com/user-attachments/assets/407fe19f-55cb-4ff7-83f1-b53bf51cdf1d">

**Comment by Noxmore** [comment]
I'm sorry, but I'm going to have to stop supporting versions older than the newest, just because of my limited free time that i would like to invest elsewhere. I really appreciate the interest in my pack though!

**Comment by thwonn** [comment]
ok then, I just overuse this resourcepack (it's in all of my modpacks and I almost never play without it)

**Comment by Noxmore** [comment]
That means a lot to me! I do wish there was some tool or something to make modern resource packs backwards compatible without all the annoying bookkeeping.

Maybe in the future if i have more time I'll take a shot at it, no promises though.

**Comment by thwonn** [comment]
I could probably make a mod for that sometime
